Content:
    - ${ROOT_DIR}/doc/content
    - ${MOOSE_DIR}/framework/doc/content
Renderer:
    type: MooseDocs.base.MaterializeRenderer
    extra-css:
        - css/zapdos.css
Extensions:
    MooseDocs.extensions.navigation:
        name: Zapdos
        home: https://shannon-lab.github.io/zapdos
        repo: https://github.com/shannon-lab/zapdos
        menu:
            Getting Started:
                Installation: getting_started/installation.md
                Using Zapdos: getting_started/using_zapdos.md
            Documentation:
                Complete Code Syntax: syntax/index.md
                Zapdos Doxygen: https://shannon-lab.github.io/zapdos/docs/doxygen/zapdos/classes.html # This will 404 until I generate a doxygen page
                MOOSE Doxygen: https://mooseframework.inl.gov/docs/doxygen/moose/classes.html
                libMesh Doxygen: https://mooseframework.inl.gov/docs/doxygen/libmesh/classes.html
                Contributing Guidelines: development/contributing.md
                Code Standards: development/code_standards.md
                List of Publications: publications.md
            Help: help.menu.md
            Citing: citing.md
    MooseDocs.extensions.template:
        active: true
    MooseDocs.extensions.appsyntax:
        executable: ${ROOT_DIR}
        includes:
            - include
        remove:
            framework: !include ${MOOSE_DIR}/framework/doc/remove.yml
    MooseDocs.extensions.common:
        shortcuts:
            framework: !include ${MOOSE_DIR}/framework/doc/globals.yml
            zapdos: !include ${ROOT_DIR}/doc/zapdos_shortcuts.yml
    MooseDocs.extensions.acronym:
        acronyms: !include ${MOOSE_DIR}/framework/doc/acronyms.yml
    MooseDocs.extensions.sqa:
        active: true
        categories:
            framework: !include ${MOOSE_DIR}/framework/doc/sqa_framework.yml
            zapdos: !include ${ROOT_DIR}/doc/sqa_zapdos.yml
        repos:
            default: https://github.com/shannon-lab/zapdos
        reports: !include ${ROOT_DIR}/doc/sqa_reports.yml
